services:
  - type: web
    name: my-hostel-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    preDeployCommand: ""
    nativePackages:
      - chromium-browser
