'use client';

import React, { useState, useEffect } from 'react';
import { useHostel } from '@/context/HostelContext';
import HostelSelector from '@/components/layout/HostelSelector';
import api from '@/lib/api';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';
import { 
  Loader2,
  Receipt,
  ChevronDown,
  Calendar,
  Download,
  Filter,
  Search,
  Table as TableIcon,
  User,
  Activity,
  ArrowRight,
  Home,
  IndianRupee,
  Clock
} from 'lucide-react';
import { cn } from '@/lib/utils';

import Sidebar from '@/components/layout/Sidebar';
import { HostelProvider } from '@/context/HostelContext';

const FeeReportsPageContent = () => {
  const { selectedHostel, setSelectedHostel } = useHostel();
  const [startDate, setStartDate] = useState(new Date(new Date().setDate(1)).toISOString().split('T')[0]);
  const [endDate, setEndDate] = useState(new Date().toISOString().split('T')[0]);
  const [studentName, setStudentName] = useState('');
  const [roomNumber, setRoomNumber] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [searchHostelName, setSearchHostelName] = useState('');
  const [reportData, setReportData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [user, setUser] = useState<any>(null);

  // Admin Filters
  const [owners, setOwners] = useState<any[]>([]);
  const [allHostels, setAllHostels] = useState<any[]>([]);
  const [selectedOwner, setSelectedOwner] = useState('all');
  const [filteredHostels, setFilteredHostels] = useState<any[]>([]);

  useEffect(() => {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
    fetchFilters();
  }, []);

  const fetchFilters = async () => {
    try {
      const res = await api.get('/finance/report/filters');
      setOwners(res.data.owners);
      setAllHostels(res.data.hostels);
    } catch (err) {
      console.error('Error fetching report filters:', err);
    }
  };

  useEffect(() => {
    if (selectedOwner === 'all') {
      setFilteredHostels([]);
      setSelectedHostel('all');
    } else {
      const hostels = allHostels.filter(h => h.owner_id.toString() === selectedOwner);
      setFilteredHostels(hostels);
      setSelectedHostel('all');
    }
  }, [selectedOwner, allHostels]);

  useEffect(() => {
    handleApplyFilter();
  }, [selectedHostel]);

  const handleApplyFilter = async () => {
    setLoading(true);
    try {
      const res = await api.get('/finance/report', {
        params: { 
          hostel_id: selectedHostel, 
          owner_id: selectedOwner === 'all' ? undefined : selectedOwner,
          fromDate: startDate, 
          toDate: endDate,
          studentName: studentName || undefined,
          roomNumber: roomNumber || undefined,
          phone: phoneNumber || undefined,
          hostel_name: searchHostelName || undefined
        }
      });
      setReportData(res.data);
    } catch (err) {
      console.error('Error fetching fee report:', err);
    } finally {
      setLoading(false);
    }
  };

  const totalCollection = reportData.reduce((sum, row) => sum + parseFloat(row.amount_paid || '0'), 0);

  const handleDownloadPdf = () => {
    const doc = new jsPDF('l', 'mm', 'a4');
    const pageWidth = (doc as any).internal.pageSize.width;
    const pageHeight = (doc as any).internal.pageSize.height;
    
    // Header Styling
    doc.setFillColor(30, 41, 59); // Dark Slate
    doc.rect(0, 0, pageWidth, 45, 'F');
    
    // Logo / Title
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('MY HOSTEL', 14, 22);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text('PREMIUM HOSTEL MANAGEMENT SYSTEM', 14, 28);

    // Report Type Badge
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.roundedRect(pageWidth - 65, 12, 50, 10, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('FEE COLLECTION REPORT', pageWidth - 40, 18.5, { align: 'center' });

    // Meta Info
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.text(`Generated by: ${user?.name || 'Admin'}`, 14, 38);
    doc.text(`Period: ${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`, pageWidth - 14, 38, { align: 'right' });

    // Summary Statistics
    doc.setFillColor(248, 250, 252); // Slate 50
    doc.roundedRect(14, 55, pageWidth - 28, 25, 3, 3, 'F');
    
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL COLLECTION', 25, 65);
    doc.text('TOTAL TRANSACTIONS', pageWidth / 2, 65);
    doc.text('HOSTEL FOCUS', pageWidth - 25, 65, { align: 'right' });
    
    doc.setTextColor(30, 41, 59); // Slate 900
    doc.setFontSize(14);
    doc.text(`Rs. ${totalCollection.toLocaleString()}`, 25, 74);
    doc.text(`${reportData.length} Payments`, pageWidth / 2, 74);
    
    let focusText = 'All';
    if (selectedOwner !== 'all') {
      const ownerName = owners.find(o => o.owner_id.toString() === selectedOwner)?.owner_name || 'Owner';
      focusText = `${ownerName}`;
      if (selectedHostel !== 'all') {
        const hostelName = allHostels.find(h => h.hostel_id.toString() === selectedHostel)?.hostel_name || 'Hostel';
        focusText += ` - ${hostelName}`;
      } else {
        focusText += ` - All Hostels`;
      }
    } else {
      focusText = 'All Owners & Hostels';
    }
    doc.text(focusText, pageWidth - 25, 74, { align: 'right' });

    // Add Filter Details in small text below summary
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    let filterDetails = [];
    if (studentName) filterDetails.push(`Student: ${studentName}`);
    if (phoneNumber) filterDetails.push(`Phone: ${phoneNumber}`);
    if (searchHostelName) filterDetails.push(`Hostel Search: ${searchHostelName}`);
    if (roomNumber) filterDetails.push(`Room: ${roomNumber}`);
    
    if (filterDetails.length > 0) {
      doc.text(`Filters: ${filterDetails.join(' | ')}`, 14, 85);
    }

    const head = [['RECEIPT ID', 'STUDENT NAME', 'PHONE', 'HOSTEL', 'ROOM', 'AMOUNT', 'COLLECTED BY', 'DATE', 'TIME']];
    const body = reportData.map(row => [
      row.receipt_id || '-',
      row.student_name?.toUpperCase() || '-',
      row.student_phone || '-',
      row.hostel_name || '-',
      row.room_number || '-',
      `Rs. ${parseFloat(row.amount_paid || '0').toLocaleString()}`,
      row.collected_by || 'System',
      new Date(row.payment_date).toLocaleDateString(),
      new Date(row.payment_timestamp || row.payment_date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    ]);

    autoTable(doc, {
      startY: 90,
      head: head,
      body: body,
      theme: 'striped',
      headStyles: { 
        fillColor: [30, 41, 59], 
        textColor: [255, 255, 255], 
        fontSize: 7,
        fontStyle: 'bold',
        cellPadding: 4,
        halign: 'left'
      },
      styles: { 
        fontSize: 7, 
        cellPadding: 4, 
        font: 'helvetica',
        textColor: [71, 85, 105],
        lineColor: [241, 245, 249],
        lineWidth: 0.1
      },
      columnStyles: {
        5: { fontStyle: 'bold', textColor: [30, 41, 59], halign: 'right' } // Amount column
      },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        doc.setFontSize(7);
        doc.setTextColor(148, 163, 184);
        const str = `Page ${doc.getNumberOfPages()}`;
        doc.text(str, pageWidth - 20, pageHeight - 10);
        doc.text(`Report generated on ${new Date().toLocaleString()}`, 14, pageHeight - 10);
      }
    });

    doc.save(`Admin_Fee_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="flex bg-[#F9FAFB] min-h-screen font-sans">
      <Sidebar role="admin" />
      
      <main className="flex-1 overflow-y-auto">
        {/* HEADER */}
        <header className="px-6 md:px-10 py-7 flex flex-col md:flex-row items-start md:items-center justify-between sticky top-0 z-30 gap-4 bg-white/90 backdrop-blur-xl border-b border-slate-200/50 shadow-sm">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <div className="w-2 h-2 rounded-full bg-indigo-500 animate-pulse" />
              <p className="text-slate-400 text-[10px] font-bold uppercase tracking-[0.2em]">Financial Intelligence</p>
            </div>
            <h1 className="text-2xl md:text-3xl font-black text-slate-900 tracking-tight flex items-center gap-3">
              Fee Collection Reports
            </h1>
          </div>
          <div className="flex items-center gap-4 w-full md:w-auto">
            <div className="flex flex-col items-end hidden md:block">
              <p className="text-xs font-bold text-slate-900">{user?.name || 'Administrator'}</p>
              <p className="text-[10px] font-medium text-slate-500 uppercase tracking-wider">Super Admin</p>
            </div>
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-600 flex items-center justify-center text-white shadow-xl shadow-indigo-200 ring-4 ring-white shrink-0">
              {user?.name?.charAt(0) || 'A'}
            </div>
          </div>
        </header>

        <div className="max-w-7xl mx-auto px-6 md:px-10 py-10 space-y-10">
        {/* FILTERS SECTION */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white p-8 md:p-10 rounded-[2.5rem] border border-slate-200/60 shadow-[0_20px_50px_rgba(0,0,0,0.02)] relative overflow-hidden"
        >
          {/* Decorative element */}
          <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-50/50 rounded-full -mr-32 -mt-32 blur-3xl pointer-events-none" />
          
          <div className="flex items-center gap-4 mb-10 relative">
            <div className="p-3 bg-indigo-50 text-indigo-600 rounded-2xl ring-1 ring-indigo-100">
              <Filter size={20} strokeWidth={2.5} />
            </div>
            <div>
              <h2 className="text-sm font-black text-slate-900 uppercase tracking-widest">Advanced Filter Suite</h2>
              <p className="text-xs text-slate-400 font-medium mt-0.5">Narrow down transactions with precision</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10 border-b border-slate-100 pb-10">
            <div className="space-y-2 group">
              <label className="text-[11px] font-black text-slate-500 uppercase tracking-widest ml-1 group-focus-within:text-indigo-600 transition-colors">Strategic Owner</label>
              <div className="relative">
                <div className="absolute left-4 top-1/2 -translate-y-1/2 w-8 h-8 rounded-xl bg-slate-50 flex items-center justify-center text-slate-400 group-focus-within:text-indigo-500 group-focus-within:bg-indigo-50 transition-all">
                  <User size={14} strokeWidth={2.5} />
                </div>
                <select 
                  value={selectedOwner}
                  onChange={(e) => setSelectedOwner(e.target.value)}
                  className="w-full bg-white border-2 border-slate-100 rounded-2xl pl-14 pr-10 py-3.5 text-xs font-bold text-slate-700 outline-none focus:border-indigo-500/20 focus:ring-4 focus:ring-indigo-500/5 transition-all shadow-sm appearance-none cursor-pointer"
                >
                  <option value="all">All Portfolio Owners</option>
                  {owners.map(owner => (
                    <option key={owner.owner_id} value={owner.owner_id}>{owner.owner_name}</option>
                  ))}
                </select>
                <ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none group-focus-within:rotate-180 transition-transform" size={16} />
              </div>
            </div>

            <div className="space-y-2 group">
              <label className="text-[11px] font-black text-slate-500 uppercase tracking-widest ml-1 group-focus-within:text-indigo-600 transition-colors">Target Hostel</label>
              <div className="relative">
                <div className="absolute left-4 top-1/2 -translate-y-1/2 w-8 h-8 rounded-xl bg-slate-50 flex items-center justify-center text-slate-400 group-focus-within:text-indigo-500 group-focus-within:bg-indigo-50 transition-all">
                  <Home size={14} strokeWidth={2.5} />
                </div>
                <select 
                  value={selectedHostel}
                  onChange={(e) => setSelectedHostel(e.target.value)}
                  disabled={selectedOwner === 'all'}
                  className="w-full bg-white border-2 border-slate-100 rounded-2xl pl-14 pr-10 py-3.5 text-xs font-bold text-slate-700 outline-none focus:border-indigo-500/20 focus:ring-4 focus:ring-indigo-500/5 transition-all shadow-sm appearance-none disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
                >
                  <option value="all">Comprehensive View (All Hostels)</option>
                  {filteredHostels.map(hostel => (
                    <option key={hostel.hostel_id} value={hostel.hostel_id}>{hostel.hostel_name}</option>
                  ))}
                </select>
                <ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none group-focus-within:rotate-180 transition-transform" size={16} />
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-6">
            <div className="space-y-2 group">
              <label className="text-[11px] font-black text-slate-500 uppercase tracking-widest ml-1 group-focus-within:text-indigo-600 transition-colors">From Date</label>
              <div className="relative">
                <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-indigo-500 transition-colors" size={14} strokeWidth={2.5} />
                <input 
                  type="date" 
                  value={startDate} 
                  onChange={(e) => setStartDate(e.target.value)}
                  className="w-full bg-white border-2 border-slate-100 rounded-2xl pl-11 pr-4 py-3.5 text-xs font-bold text-slate-700 outline-none focus:border-indigo-500/20 focus:ring-4 focus:ring-indigo-500/5 transition-all shadow-sm"
                />
              </div>
            </div>

            <div className="space-y-2 group">
              <label className="text-[11px] font-black text-slate-500 uppercase tracking-widest ml-1 group-focus-within:text-indigo-600 transition-colors">To Date</label>
              <div className="relative">
                <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-indigo-500 transition-colors" size={14} strokeWidth={2.5} />
                <input 
                  type="date" 
                  value={endDate} 
                  onChange={(e) => setEndDate(e.target.value)}
                  className="w-full bg-white border-2 border-slate-100 rounded-2xl pl-11 pr-4 py-3.5 text-xs font-bold text-slate-700 outline-none focus:border-indigo-500/20 focus:ring-4 focus:ring-indigo-500/5 transition-all shadow-sm"
                />
              </div>
            </div>

            <div className="space-y-2 group">
              <label className="text-[11px] font-black text-slate-500 uppercase tracking-widest ml-1 group-focus-within:text-indigo-600 transition-colors">Student Identity</label>
              <div className="relative">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-indigo-500 transition-colors" size={14} strokeWidth={2.5} />
                <input 
                  type="text" 
                  placeholder="Name of resident..."
                  value={studentName}
                  onChange={(e) => setStudentName(e.target.value)}
                  className="w-full bg-white border-2 border-slate-100 rounded-2xl pl-11 pr-4 py-3.5 text-xs font-bold text-slate-700 outline-none focus:border-indigo-500/20 focus:ring-4 focus:ring-indigo-500/5 transition-all shadow-sm placeholder:text-slate-300"
                />
              </div>
            </div>

            <div className="space-y-2 group">
              <label className="text-[11px] font-black text-slate-500 uppercase tracking-widest ml-1 group-focus-within:text-indigo-600 transition-colors">Contact Number</label>
              <div className="relative">
                <Activity className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-indigo-500 transition-colors" size={14} strokeWidth={2.5} />
                <input 
                  type="text" 
                  placeholder="Phone digits..."
                  value={phoneNumber}
                  onChange={(e) => setPhoneNumber(e.target.value)}
                  className="w-full bg-white border-2 border-slate-100 rounded-2xl pl-11 pr-4 py-3.5 text-xs font-bold text-slate-700 outline-none focus:border-indigo-500/20 focus:ring-4 focus:ring-indigo-500/5 transition-all shadow-sm placeholder:text-slate-300"
                />
              </div>
            </div>

            <div className="space-y-2 group">
              <label className="text-[11px] font-black text-slate-500 uppercase tracking-widest ml-1 group-focus-within:text-indigo-600 transition-colors">Hostel Keyword</label>
              <div className="relative">
                <Home className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 group-focus-within:text-indigo-500 transition-colors" size={14} strokeWidth={2.5} />
                <input 
                  type="text" 
                  placeholder="Search location..."
                  value={searchHostelName}
                  onChange={(e) => setSearchHostelName(e.target.value)}
                  className="w-full bg-white border-2 border-slate-100 rounded-2xl pl-11 pr-4 py-3.5 text-xs font-bold text-slate-700 outline-none focus:border-indigo-500/20 focus:ring-4 focus:ring-indigo-500/5 transition-all shadow-sm placeholder:text-slate-300"
                />
              </div>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 mt-12">
            <button 
              onClick={handleApplyFilter}
              disabled={loading}
              className="flex-[2] flex items-center justify-center gap-3 bg-indigo-600 hover:bg-indigo-700 text-white font-black text-xs uppercase tracking-[0.2em] py-4 rounded-2xl transition-all shadow-xl shadow-indigo-200 active:scale-[0.98] disabled:opacity-50"
            >
              {loading ? <Loader2 size={18} className="animate-spin" /> : <Search size={18} strokeWidth={2.5} />}
              Execute Query
            </button>
            <button 
              onClick={handleDownloadPdf}
              disabled={loading || reportData.length === 0}
              className="flex-1 flex items-center justify-center gap-3 bg-slate-900 hover:bg-slate-800 text-white font-black text-xs uppercase tracking-[0.2em] py-4 rounded-2xl transition-all shadow-xl shadow-slate-200 active:scale-[0.98] disabled:opacity-50"
            >
              <Download size={18} strokeWidth={2.5} />
              Export PDF
            </button>
          </div>
        </motion.div>

        {/* SUMMARY SECTION */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="bg-gradient-to-r from-indigo-600 via-indigo-500 to-violet-600 rounded-[2.5rem] p-10 text-white flex flex-col md:flex-row items-center justify-between shadow-[0_20px_50px_rgba(79,70,229,0.2)] relative overflow-hidden"
        >
          {/* Abstract background shapes */}
          <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
            <div className="absolute -top-24 -left-24 w-64 h-64 bg-white/10 rounded-full blur-3xl" />
            <div className="absolute -bottom-24 -right-24 w-64 h-64 bg-indigo-400/20 rounded-full blur-3xl" />
          </div>

          <div className="flex items-center gap-6 mb-6 md:mb-0 relative">
            <div className="w-16 h-16 bg-white/20 rounded-2xl flex items-center justify-center backdrop-blur-md border border-white/20 shadow-inner">
              <IndianRupee size={32} className="text-white" strokeWidth={2.5} />
            </div>
            <div>
              <p className="text-indigo-100 text-[11px] font-black uppercase tracking-[0.2em] mb-1">Cumulative Revenue</p>
              <div className="flex items-baseline gap-2">
                <span className="text-4xl font-black tracking-tighter">₹ {totalCollection.toLocaleString()}</span>
                <span className="text-indigo-200 text-xs font-bold uppercase tracking-wider">Gross</span>
              </div>
            </div>
          </div>
          <div className="text-center md:text-right relative">
            <p className="text-indigo-100 text-[11px] font-black uppercase tracking-[0.2em] mb-2">Transaction Volume</p>
            <div className="bg-white/10 backdrop-blur-md border border-white/10 px-6 py-2 rounded-full inline-block">
              <p className="text-2xl font-black tracking-tight">{reportData.length} <span className="text-sm font-medium opacity-80 uppercase tracking-widest ml-1">Entries</span></p>
            </div>
          </div>
        </motion.div>

        {/* TABLE SECTION */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-white rounded-[2.5rem] border border-slate-200/60 shadow-[0_20px_50px_rgba(0,0,0,0.02)] overflow-hidden"
        >
          <div className="p-8 border-b border-slate-50 flex items-center justify-between bg-white">
            <div className="flex items-center gap-4">
              <div className="p-3 bg-slate-50 text-slate-500 rounded-2xl ring-1 ring-slate-100">
                <TableIcon size={20} strokeWidth={2.5} />
              </div>
              <div>
                <h2 className="text-sm font-black text-slate-900 uppercase tracking-widest">Master Transaction Ledger</h2>
                <p className="text-xs text-slate-400 font-medium mt-0.5">Real-time financial audit trail</p>
              </div>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/50">
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Ref. Receipt</th>
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Beneficiary</th>
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Asset Details</th>
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Quantum</th>
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Timestamp</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {loading ? (
                  <tr>
                    <td colSpan={5} className="px-8 py-24 text-center">
                      <div className="flex flex-col items-center gap-4">
                        <Loader2 className="animate-spin text-indigo-500" size={40} strokeWidth={1.5} />
                        <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Aggregating Financial Data...</p>
                      </div>
                    </td>
                  </tr>
                ) : reportData.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="px-8 py-24 text-center">
                      <div className="flex flex-col items-center gap-4 opacity-40">
                        <Receipt size={48} strokeWidth={1.5} />
                        <p className="text-xs font-bold uppercase tracking-widest">No matching records found</p>
                      </div>
                    </td>
                  </tr>
                ) : (
                  reportData.map((row, idx) => (
                    <motion.tr 
                      key={row.receipt_id || idx}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: idx * 0.03 }}
                      className="hover:bg-slate-50/50 transition-colors group cursor-default"
                    >
                      <td className="px-8 py-6">
                        <div className="flex flex-col">
                          <span className="text-[11px] font-black text-indigo-600 bg-indigo-50 px-2.5 py-1 rounded-lg w-fit mb-1 uppercase tracking-wider">
                            #{row.receipt_id || 'N/A'}
                          </span>
                          <span className="text-[10px] font-medium text-slate-400 flex items-center gap-1">
                            <Clock size={10} />
                            Verified Payment
                          </span>
                        </div>
                      </td>
                      <td className="px-8 py-6">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center text-slate-500 font-black text-xs group-hover:bg-indigo-500 group-hover:text-white transition-all shadow-sm">
                            {row.student_name?.charAt(0) || 'S'}
                          </div>
                          <div className="flex flex-col">
                            <span className="text-xs font-black text-slate-900 uppercase tracking-tight">{row.student_name || 'Anonymous Student'}</span>
                            <span className="text-[10px] font-bold text-slate-400">{row.student_phone || 'No Contact'}</span>
                          </div>
                        </div>
                      </td>
                      <td className="px-8 py-6">
                        <div className="flex flex-col gap-1">
                          <div className="flex items-center gap-1.5 text-xs font-bold text-slate-700">
                            <Home size={12} className="text-slate-400" />
                            {row.hostel_name || 'Global'}
                          </div>
                          <div className="flex items-center gap-1.5 text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                            <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                            Unit: {row.room_number || 'NA'}
                          </div>
                        </div>
                      </td>
                      <td className="px-8 py-6">
                        <div className="flex flex-col">
                          <span className="text-sm font-black text-slate-900 tracking-tighter">
                            ₹ {parseFloat(row.amount_paid || '0').toLocaleString()}
                          </span>
                          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest flex items-center gap-1">
                            By: {row.collected_by || 'System'}
                          </span>
                        </div>
                      </td>
                      <td className="px-8 py-6 text-right">
                        <div className="flex flex-col items-end">
                          <span className="text-xs font-black text-slate-900">
                            {new Date(row.payment_date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}
                          </span>
                          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">
                            {new Date(row.payment_timestamp || row.payment_date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                          </span>
                        </div>
                      </td>
                    </motion.tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
          
          <div className="p-8 bg-slate-50/30 border-t border-slate-50 flex items-center justify-between">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
              End of ledger • {reportData.length} records retrieved
            </p>
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.5)]" />
              <p className="text-[10px] font-black text-slate-900 uppercase tracking-widest">System Synchronized</p>
            </div>
          </div>
        </motion.div>
      </div>
    </main>
  </div>
);
};

const FeeReportsPage = () => {
  return (
    <HostelProvider>
      <FeeReportsPageContent />
    </HostelProvider>
  );
};

export default FeeReportsPage;
