'use client';

import React, { useState, useEffect } from 'react';
import { useHostel } from '@/context/HostelContext';
import HostelSelector from '@/components/layout/HostelSelector';
import api from '@/lib/api';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';
import { 
  Loader2,
  Receipt,
  ChevronDown,
  Calendar,
  Download,
  FileText,
  Filter,
  Search,
  Table as TableIcon,
  CreditCard,
  User,
  Activity,
  ArrowRight,
  Home
} from 'lucide-react';
import { cn } from '@/lib/utils';

const ReportsPage = () => {
  const { selectedHostel } = useHostel();
  const [reportType, setReportType] = useState('revenue');
  const [startDate, setStartDate] = useState(new Date(new Date().setDate(1)).toISOString().split('T')[0]);
  const [endDate, setEndDate] = useState(new Date().toISOString().split('T')[0]);
  const [paymentMode, setPaymentMode] = useState('all');
  const [reportData, setReportData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
  }, []);

  const handleGenerateReport = async () => {
    setLoading(true);
    try {
      const res = await api.get('/owner/reports', {
        params: { 
          type: reportType, 
          hostel_id: selectedHostel, 
          startDate, 
          endDate, 
          paymentMode 
        }
      });
      setReportData(res.data);
    } catch (err) {
      console.error('Error generating report:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPdf = () => {
    const doc = new jsPDF();
    const pageWidth = (doc as any).internal.pageSize.width;
    const pageHeight = (doc as any).internal.pageSize.height;
    
    // Header Styling
    doc.setFillColor(30, 41, 59); // Dark Slate
    doc.rect(0, 0, pageWidth, 45, 'F');
    
    // Logo / Title
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('MY HOSTEL', 14, 22);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text('PREMIUM SAAS PORTFOLIO AUDIT', 14, 28);

    // Report Type Badge
    const reportLabel = `${reportType.toUpperCase()} AUDIT`;
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.roundedRect(pageWidth - 65, 12, 50, 10, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(reportLabel, pageWidth - 40, 18.5, { align: 'center' });

    // Meta Info
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.text(`Generated by: ${user?.name || 'Captain'}`, 14, 38);
    doc.text(`Period: ${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`, pageWidth - 14, 38, { align: 'right' });

    // Summary Statistics
    const totalAmount = reportData.reduce((sum, row) => sum + parseFloat(row.amount || '0'), 0);
    
    doc.setFillColor(248, 250, 252); // Slate 50
    doc.roundedRect(14, 55, pageWidth - 28, 25, 3, 3, 'F');
    
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL VOLUME', 25, 65);
    doc.text('TOTAL ENTRIES', pageWidth / 2, 65);
    doc.text('PORTFOLIO FOCUS', pageWidth - 25, 65, { align: 'right' });
    
    doc.setTextColor(30, 41, 59); // Slate 900
    doc.setFontSize(14);
    doc.text(`Rs. ${totalAmount.toLocaleString()}`, 25, 74);
    doc.text(`${reportData.length} Records`, pageWidth / 2, 74);
    doc.text(selectedHostel === 'all' ? 'Entire Portfolio' : 'Specific Unit', pageWidth - 25, 74, { align: 'right' });

    let head: string[][] = [];
    let body: any[][] = [];

    if (reportType === 'revenue') {
      head = [['DATE', 'NAME', 'HOSTEL NAME', 'ROOM NUM', 'AMOUNT', 'METHOD', 'REFERENCE ID']];
      body = reportData.map(row => [
        new Date(row.date).toLocaleDateString(),
        row.student_name?.toUpperCase() || '-',
        row.hostel_name?.toUpperCase() || '-',
        row.room_number || '-',
        `Rs. ${parseFloat(row.amount || '0').toLocaleString()}`,
        row.mode?.toUpperCase() || '-',
        row.transaction_id || row.receipt_id || '-'
      ]);
    } else {
      head = [['DATE', 'AUDIT DETAIL', 'HOSTEL NAME', 'AMOUNT', 'CATEGORY', 'AUTHORIZED BY']];
      body = reportData.map(row => [
        new Date(row.date).toLocaleDateString(),
        row.detail?.toUpperCase() || '-',
        row.hostel_name?.toUpperCase() || '-',
        `Rs. ${parseFloat(row.amount || '0').toLocaleString()}`,
        row.mode?.toUpperCase() || '-',
        row.received_by?.toUpperCase() || '-'
      ]);
    }

    autoTable(doc, {
      startY: 90,
      head: head,
      body: body,
      theme: 'striped',
      headStyles: { 
        fillColor: [30, 41, 59] as [number, number, number], 
        textColor: [255, 255, 255] as [number, number, number], 
        fontSize: 7,
        fontStyle: 'bold',
        cellPadding: 4,
        halign: 'left'
      },
      styles: { 
        fontSize: 7, 
        cellPadding: 4, 
        font: 'helvetica',
        textColor: [71, 85, 105] as [number, number, number],
        lineColor: [241, 245, 249] as [number, number, number],
        lineWidth: 0.1
      },
      columnStyles: {
        4: { fontStyle: 'bold', textColor: [30, 41, 59] as [number, number, number], halign: 'right' } // Amount column
      },
      alternateRowStyles: { fillColor: [250, 250, 250] as [number, number, number] },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        // Footer
        doc.setFontSize(7);
        doc.setTextColor(148, 163, 184);
        const str = `Page ${doc.getNumberOfPages()}`;
        doc.text(str, pageWidth - 20, pageHeight - 10);
        doc.text(`Audit generated on ${new Date().toLocaleString()}`, 14, pageHeight - 10);
      }
    });

    doc.save(`${reportType}_audit_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="min-h-screen">
      {/* HEADER */}
      <header className="px-4 md:px-8 py-4 md:py-8 flex flex-col md:flex-row items-start md:items-center justify-between sticky top-0 z-20 gap-4 bg-[#FDFDFF]/80 backdrop-blur-md">
        <div>
          <h1 className="text-xl md:text-2xl font-black text-slate-900 tracking-tight">Reports & Analytics Engine</h1>
          <p className="text-slate-400 text-[8px] md:text-[10px] font-bold uppercase tracking-[0.2em] mt-1">Audit Logs & Portfolio Data Exports</p>
        </div>
        <div className="flex items-center gap-2 md:gap-4 w-full md:w-auto">
          <div className="flex-1 md:flex-none">
            <HostelSelector />
          </div>
          <div className="w-8 h-8 md:w-10 md:h-10 rounded-xl bg-indigo-600 flex items-center justify-center text-white shadow-lg shadow-indigo-600/20 shrink-0">
            {user?.name?.charAt(0) || 'C'}
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 md:px-8 pb-24 space-y-8 md:space-y-12 mt-8">
        {/* CONFIGURATION CARD */}
        <motion.div 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white p-6 md:p-10 rounded-[2.5rem] border border-slate-200/60 shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)]"
        >
          <div className="flex items-center gap-3 mb-8 md:mb-12">
            <div className="p-2.5 bg-indigo-600 rounded-2xl shadow-lg shadow-indigo-600/20">
              <Filter className="text-white" size={20} />
            </div>
            <h2 className="text-[10px] md:text-xs font-black text-slate-900 uppercase tracking-widest">Report Configuration</h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6 md:gap-8">
            <div className="space-y-2">
              <label className="text-[8px] font-black text-slate-400 uppercase tracking-widest ml-1">Report Focus</label>
              <div className="relative">
                <select 
                  value={reportType} 
                  onChange={(e) => setReportType(e.target.value)}
                  className="w-full bg-slate-50/50 border border-slate-100 rounded-2xl px-4 py-3.5 text-[10px] md:text-xs font-bold text-slate-700 outline-none focus:border-indigo-200 transition-all appearance-none shadow-sm focus:bg-white"
                >
                  <option value="revenue">Revenue Audit</option>
                  <option value="expenses">Expense Audit</option>
                </select>
                <ChevronDown size={14} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[8px] font-black text-slate-400 uppercase tracking-widest ml-1">Start Period</label>
              <input 
                type="date" 
                value={startDate} 
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full bg-slate-50/50 border border-slate-100 rounded-2xl px-4 py-3.5 text-[10px] md:text-xs font-bold text-slate-700 outline-none focus:border-indigo-200 transition-all shadow-sm focus:bg-white"
              />
            </div>

            <div className="space-y-2">
              <label className="text-[8px] font-black text-slate-400 uppercase tracking-widest ml-1">End Period</label>
              <input 
                type="date" 
                value={endDate} 
                onChange={(e) => setEndDate(e.target.value)}
                className="w-full bg-slate-50/50 border border-slate-100 rounded-2xl px-4 py-3.5 text-[10px] md:text-xs font-bold text-slate-700 outline-none focus:border-indigo-200 transition-all shadow-sm focus:bg-white"
              />
            </div>

            <div className="space-y-2">
              <label className="text-[8px] font-black text-slate-400 uppercase tracking-widest ml-1">Filter Mode</label>
              <div className="relative">
                <select 
                  value={paymentMode} 
                  onChange={(e) => setPaymentMode(e.target.value)}
                  className="w-full bg-slate-50/50 border border-slate-100 rounded-2xl px-4 py-3.5 text-[10px] md:text-xs font-bold text-slate-700 outline-none focus:border-indigo-200 transition-all appearance-none shadow-sm focus:bg-white"
                >
                  <option value="all">All Modes</option>
                  <option value="UPI">UPI</option>
                  <option value="Cash">Cash</option>
                  <option value="Bank Transfer">Bank Transfer</option>
                </select>
                <ChevronDown size={14} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
              </div>
            </div>

            <div className="flex items-end gap-3 pt-2 sm:pt-0">
              <button 
                onClick={handleGenerateReport}
                disabled={loading}
                className="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white rounded-2xl px-6 py-3.5 text-[10px] font-black uppercase tracking-widest shadow-xl shadow-indigo-100 transition-all flex items-center justify-center gap-2 disabled:opacity-50 active:scale-95"
              >
                {loading ? <Loader2 size={16} className="animate-spin" /> : <Activity size={16} />}
                Generate
              </button>
              {reportData.length > 0 && (
                <button 
                  onClick={handleDownloadPdf}
                  className="bg-emerald-50 hover:bg-emerald-100 text-emerald-600 rounded-2xl px-5 py-3.5 border border-emerald-100/50 shadow-sm transition-all active:scale-95"
                >
                  <Download size={20} />
                </button>
              )}
            </div>
          </div>
        </motion.div>

        {/* PREVIEW AREA */}
        <AnimatePresence mode="wait">
          {reportData.length > 0 ? (
            <motion.div 
              key="table"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="bg-white rounded-[2.5rem] border border-slate-200/60 shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] overflow-hidden"
            >
              <div className="p-6 md:p-10 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600 border border-indigo-100/50">
                    <TableIcon size={18} />
                  </div>
                  <h2 className="text-[10px] md:text-xs font-black text-[#1E293B] uppercase tracking-widest">Previewing {reportData.length} Entries</h2>
                </div>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-slate-50/50">
                      <th className="px-6 md:px-10 py-5 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Date</th>
                      <th className="px-6 md:px-10 py-5 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">
                        {reportType === 'revenue' ? 'Resident Name' : 'Audit Detail'}
                      </th>
                      <th className="px-6 md:px-10 py-5 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Unit</th>
                      {reportType === 'revenue' && (
                        <th className="px-6 md:px-10 py-5 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Room</th>
                      )}
                      <th className="px-6 md:px-10 py-5 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest text-right">Amount</th>
                      <th className="px-6 md:px-10 py-5 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest text-center">Mode</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-50">
                    {reportData.map((row, idx) => (
                      <tr key={idx} className="hover:bg-slate-50/30 transition-all group">
                        <td className="px-6 md:px-10 py-6 text-[10px] font-bold text-[#64748B] whitespace-nowrap">
                          {new Date(row.date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
                        </td>
                        <td className="px-6 md:px-10 py-6">
                          <p className="text-[11px] font-black text-[#1E293B] group-hover:text-indigo-600 transition-all truncate max-w-[120px] md:max-w-none">
                            {reportType === 'revenue' ? (row.student_name || 'N/A') : (row.detail || 'N/A')}
                          </p>
                        </td>
                        <td className="px-6 md:px-10 py-6">
                          <div className="flex items-center gap-2.5">
                            <Home size={14} className="text-[#94A3B8] shrink-0" />
                            <span className="text-[10px] font-bold text-[#475569] truncate max-w-[100px]">{row.hostel_name || 'N/A'}</span>
                          </div>
                        </td>
                        {reportType === 'revenue' && (
                          <td className="px-6 md:px-10 py-6 text-[10px] font-bold text-[#475569]">
                            #{row.room_number || 'N/A'}
                          </td>
                        )}
                        <td className="px-6 md:px-10 py-6 text-right">
                          <span className="text-[11px] font-black text-[#1E293B]">₹{parseFloat(row.amount || '0').toLocaleString()}</span>
                        </td>
                        <td className="px-6 md:px-10 py-6 text-center">
                          <span className={cn(
                            "px-3 py-1.5 rounded-lg text-[8px] font-black uppercase tracking-tighter whitespace-nowrap border",
                            row.mode === 'Cash' ? "bg-amber-50 text-amber-700 border-amber-100" : "bg-indigo-50 text-indigo-700 border-indigo-100"
                          )}>
                            {row.mode}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </motion.div>
          ) : (
            <motion.div 
              key="empty"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="bg-white p-12 md:p-24 rounded-[3rem] border-2 border-dashed border-slate-100 flex flex-col items-center justify-center text-center"
            >
              <div className="w-16 h-16 md:w-24 md:h-24 bg-slate-50 rounded-full flex items-center justify-center mb-6 md:mb-10 shadow-inner border border-white">
                <FileText size={40} className="text-slate-200" />
              </div>
              <h3 className="text-base md:text-xl font-black text-[#1E293B] tracking-tight">No Audit Data Generated</h3>
              <p className="text-[#94A3B8] text-[9px] md:text-[11px] font-bold uppercase tracking-[0.2em] mt-3 max-w-xs leading-relaxed">
                Configure your audit parameters and click generate to see live preview.
              </p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default ReportsPage;