'use client';

import React, { useState, useEffect } from 'react';
import api from '@/lib/api';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';
import { 
  Loader2,
  Receipt,
  Calendar,
  Download,
  Filter,
  Search,
  Table as TableIcon,
  CreditCard,
  User,
  Activity,
  Home,
  Clock
} from 'lucide-react';
import { cn } from '@/lib/utils';
import HostelSelector from '@/components/layout/HostelSelector';
import { useHostel } from '@/context/HostelContext';

interface FeeReportProps {
  role: 'owner' | 'admin';
}

const FeeCollectionReport = ({ role }: FeeReportProps) => {
  const { selectedHostel } = useHostel();
  const [startDate, setStartDate] = useState(new Date(new Date().setDate(1)).toISOString().split('T')[0]);
  const [endDate, setEndDate] = useState(new Date().toISOString().split('T')[0]);
  const [studentName, setStudentName] = useState('');
  const [roomNumber, setRoomNumber] = useState('');
  const [reportData, setReportData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
    handleGenerateReport();
  }, [selectedHostel]);

  const handleGenerateReport = async () => {
    setLoading(true);
    try {
      const res = await api.get('/finance/report', {
        params: { 
          hostel_id: selectedHostel, 
          fromDate: startDate, 
          toDate: endDate, 
          studentName: studentName || undefined,
          roomNumber: roomNumber || undefined
        }
      });
      setReportData(res.data);
    } catch (err) {
      console.error('Error generating report:', err);
    } finally {
      setLoading(false);
    }
  };

  const totalCollection = reportData.reduce((sum, row) => sum + parseFloat(row.amount_paid || '0'), 0);

  const handleDownloadPdf = () => {
    const doc = new jsPDF();
    const pageWidth = (doc as any).internal.pageSize.width;
    const pageHeight = (doc as any).internal.pageSize.height;
    
    // Header Styling
    doc.setFillColor(30, 41, 59); // Dark Slate
    doc.rect(0, 0, pageWidth, 45, 'F');
    
    // Logo / Title
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('MY HOSTEL', 14, 22);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text('FEE COLLECTION REPORT', 14, 28);

    // Report Type Badge
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.roundedRect(pageWidth - 65, 12, 50, 10, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('FEE REPORT', pageWidth - 40, 18.5, { align: 'center' });

    // Meta Info
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.text(`Generated by: ${user?.name || 'Captain'}`, 14, 38);
    doc.text(`Period: ${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`, pageWidth - 14, 38, { align: 'right' });

    // Summary Statistics
    doc.setFillColor(248, 250, 252); // Slate 50
    doc.roundedRect(14, 55, pageWidth - 28, 25, 3, 3, 'F');
    
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL COLLECTION', 25, 65);
    doc.text('TOTAL TRANSACTIONS', pageWidth / 2, 65);
    doc.text('HOSTEL FOCUS', pageWidth - 25, 65, { align: 'right' });
    
    doc.setTextColor(30, 41, 59); // Slate 900
    doc.setFontSize(14);
    doc.text(`Rs. ${totalCollection.toLocaleString()}`, 25, 74);
    doc.text(`${reportData.length} Records`, pageWidth / 2, 74);
    doc.text(selectedHostel === 'all' ? 'Entire Portfolio' : (reportData[0]?.hostel_name || 'Specific Unit'), pageWidth - 25, 74, { align: 'right' });

    const head = [['RECEIPT ID', 'STUDENT NAME', 'ROOM', 'AMOUNT', 'DATE & TIME', 'MODE']];
    const body = reportData.map(row => [
      row.receipt_id || '-',
      row.student_name?.toUpperCase() || '-',
      row.room_number || '-',
      `Rs. ${parseFloat(row.amount_paid || '0').toLocaleString()}`,
      `${new Date(row.payment_date).toLocaleDateString()} ${new Date(row.payment_date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`,
      row.payment_mode?.toUpperCase() || '-'
    ]);

    autoTable(doc, {
      startY: 90,
      head: head,
      body: body,
      theme: 'striped',
      headStyles: { 
        fillColor: [30, 41, 59] as [number, number, number], 
        textColor: [255, 255, 255] as [number, number, number], 
        fontSize: 7,
        fontStyle: 'bold',
        cellPadding: 4,
        halign: 'left'
      },
      styles: { 
        fontSize: 7, 
        cellPadding: 4, 
        font: 'helvetica',
        textColor: [71, 85, 105] as [number, number, number],
        lineColor: [241, 245, 249] as [number, number, number],
        lineWidth: 0.1
      },
      columnStyles: {
        3: { fontStyle: 'bold', textColor: [30, 41, 59] as [number, number, number], halign: 'right' } // Amount column
      },
      alternateRowStyles: { fillColor: [250, 250, 250] as [number, number, number] },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        // Footer
        doc.setFontSize(7);
        doc.setTextColor(148, 163, 184);
        const str = `Page ${doc.getNumberOfPages()}`;
        doc.text(str, pageWidth - 20, pageHeight - 10);
        doc.text(`Fee report generated on ${new Date().toLocaleString()}`, 14, pageHeight - 10);
      }
    });

    doc.save(`Fee_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="min-h-screen bg-[#FDFDFF]">
      {/* HEADER */}
      <header className="px-4 md:px-8 py-6 md:py-8 flex flex-col md:flex-row items-start md:items-center justify-between sticky top-0 z-20 gap-4 bg-[#FDFDFF]/80 backdrop-blur-md border-b border-slate-100">
        <div>
          <h1 className="text-xl md:text-2xl font-black text-slate-900 tracking-tight flex items-center gap-3">
            <Receipt className="text-indigo-600" size={28} />
            Fee Collection Report
          </h1>
          <p className="text-slate-400 text-[10px] font-bold uppercase tracking-[0.2em] mt-1">Detailed Transaction Audit & Revenue Tracking</p>
        </div>
        <div className="flex items-center gap-3 md:gap-4 w-full md:w-auto">
          <HostelSelector />
          <div className="w-10 h-10 rounded-xl bg-indigo-600 flex items-center justify-center text-white shadow-lg shadow-indigo-600/20 shrink-0 font-bold">
            {user?.name?.charAt(0) || 'C'}
          </div>
        </div>
      </header>

      <main className="p-4 md:p-8 space-y-8 max-w-[1600px] mx-auto">
        {/* FILTERS SECTION */}
        <section className="bg-white rounded-[2rem] p-6 md:p-8 border border-slate-100 shadow-sm relative overflow-hidden group">
          <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-50/50 rounded-full blur-3xl -mr-32 -mt-32 transition-colors group-hover:bg-indigo-100/50" />
          
          <div className="relative z-10 space-y-6">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-8 h-8 rounded-lg bg-indigo-50 flex items-center justify-center text-indigo-600">
                <Filter size={18} />
              </div>
              <h2 className="font-bold text-slate-800 tracking-tight">Report Filters</h2>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">From Date</label>
                <div className="relative">
                  <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                  <input
                    type="date"
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border-none rounded-2xl text-sm font-bold text-slate-700 focus:ring-2 focus:ring-indigo-500/20 transition-all"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">To Date</label>
                <div className="relative">
                  <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                  <input
                    type="date"
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border-none rounded-2xl text-sm font-bold text-slate-700 focus:ring-2 focus:ring-indigo-500/20 transition-all"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Student Name</label>
                <div className="relative">
                  <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                  <input
                    type="text"
                    placeholder="Search by name..."
                    value={studentName}
                    onChange={(e) => setStudentName(e.target.value)}
                    className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border-none rounded-2xl text-sm font-bold text-slate-700 focus:ring-2 focus:ring-indigo-500/20 transition-all placeholder:text-slate-300"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">Room Number</label>
                <div className="relative">
                  <Home className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                  <input
                    type="text"
                    placeholder="Room no..."
                    value={roomNumber}
                    onChange={(e) => setRoomNumber(e.target.value)}
                    className="w-full pl-12 pr-4 py-3.5 bg-slate-50 border-none rounded-2xl text-sm font-bold text-slate-700 focus:ring-2 focus:ring-indigo-500/20 transition-all placeholder:text-slate-300"
                  />
                </div>
              </div>
            </div>

            <div className="flex flex-wrap items-center gap-4 pt-4 border-t border-slate-50">
              <button
                onClick={handleGenerateReport}
                disabled={loading}
                className="px-8 py-3.5 bg-slate-900 text-white rounded-2xl font-bold text-sm shadow-xl shadow-slate-900/10 hover:bg-slate-800 transition-all active:scale-95 disabled:opacity-50 flex items-center gap-2"
              >
                {loading ? <Loader2 size={18} className="animate-spin" /> : <Activity size={18} />}
                Apply Filters
              </button>
              
              <button
                onClick={handleDownloadPdf}
                disabled={loading || reportData.length === 0}
                className="px-8 py-3.5 bg-indigo-600 text-white rounded-2xl font-bold text-sm shadow-xl shadow-indigo-600/10 hover:bg-indigo-700 transition-all active:scale-95 disabled:opacity-50 flex items-center gap-2"
              >
                <Download size={18} />
                Download PDF
              </button>
            </div>
          </div>
        </section>

        {/* SUMMARY CARDS */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-indigo-600 rounded-[2rem] p-8 text-white shadow-xl shadow-indigo-600/20 relative overflow-hidden group">
            <div className="absolute bottom-0 right-0 w-32 h-32 bg-white/10 rounded-full blur-2xl -mb-16 -mr-16 group-hover:scale-150 transition-transform duration-700" />
            <div className="relative z-10">
              <p className="text-indigo-100 text-[10px] font-black uppercase tracking-[0.2em] mb-2">Total Collection</p>
              <h3 className="text-3xl font-black tracking-tight">₹{totalCollection.toLocaleString()}</h3>
              <p className="text-indigo-200 text-[10px] mt-4 flex items-center gap-1.5 font-bold">
                <Activity size={12} />
                Updated based on filters
              </p>
            </div>
          </div>

          <div className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm relative overflow-hidden group">
            <div className="relative z-10">
              <p className="text-slate-400 text-[10px] font-black uppercase tracking-[0.2em] mb-2">Total Transactions</p>
              <h3 className="text-3xl font-black text-slate-900 tracking-tight">{reportData.length}</h3>
              <p className="text-slate-400 text-[10px] mt-4 flex items-center gap-1.5 font-bold">
                <TableIcon size={12} className="text-indigo-600" />
                Filtered entries found
              </p>
            </div>
          </div>

          <div className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-sm relative overflow-hidden group">
            <div className="relative z-10">
              <p className="text-slate-400 text-[10px] font-black uppercase tracking-[0.2em] mb-2">Average Payment</p>
              <h3 className="text-3xl font-black text-slate-900 tracking-tight">
                ₹{reportData.length > 0 ? Math.round(totalCollection / reportData.length).toLocaleString() : '0'}
              </h3>
              <p className="text-slate-400 text-[10px] mt-4 flex items-center gap-1.5 font-bold">
                <CreditCard size={12} className="text-indigo-600" />
                Per transaction average
              </p>
            </div>
          </div>
        </section>

        {/* TABLE SECTION */}
        <section className="bg-white rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden">
          <div className="p-6 md:p-8 border-b border-slate-50 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center text-slate-400">
                <TableIcon size={20} />
              </div>
              <div>
                <h2 className="font-black text-slate-900 tracking-tight">Transaction Ledger</h2>
                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-0.5">Live Data Feed</p>
              </div>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50/50">
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Receipt ID</th>
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Student Details</th>
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Room</th>
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Payment Info</th>
                  <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                <AnimatePresence mode="popLayout">
                  {loading ? (
                    <tr>
                      <td colSpan={5} className="px-8 py-20 text-center">
                        <div className="flex flex-col items-center gap-4">
                          <Loader2 size={32} className="text-indigo-600 animate-spin" />
                          <p className="text-slate-400 text-sm font-bold animate-pulse">Fetching ledger data...</p>
                        </div>
                      </td>
                    </tr>
                  ) : reportData.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="px-8 py-20 text-center">
                        <div className="flex flex-col items-center gap-4">
                          <div className="w-16 h-16 rounded-3xl bg-slate-50 flex items-center justify-center text-slate-300">
                            <Search size={32} />
                          </div>
                          <div>
                            <p className="text-slate-900 font-bold">No transactions found</p>
                            <p className="text-slate-400 text-xs mt-1">Try adjusting your filters or date range</p>
                          </div>
                        </div>
                      </td>
                    </tr>
                  ) : (
                    reportData.map((row, idx) => (
                      <motion.tr 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: idx * 0.05 }}
                        key={row.receipt_id + idx} 
                        className="hover:bg-slate-50/50 transition-colors group"
                      >
                        <td className="px-8 py-6">
                          <div className="flex flex-col">
                            <span className="text-xs font-black text-slate-900 tracking-wide uppercase">{row.receipt_id || 'N/A'}</span>
                            <span className="text-[10px] font-bold text-slate-400 mt-1 uppercase tracking-tighter">Verified Entry</span>
                          </div>
                        </td>
                        <td className="px-8 py-6">
                          <div className="flex items-center gap-3">
                            <div className="w-9 h-9 rounded-xl bg-indigo-50 flex items-center justify-center text-indigo-600 font-black text-xs">
                              {row.student_name?.charAt(0)}
                            </div>
                            <div className="flex flex-col">
                              <span className="text-sm font-bold text-slate-800">{row.student_name?.toUpperCase()}</span>
                              <span className="text-[10px] font-medium text-slate-400 uppercase tracking-widest">{row.hostel_name}</span>
                            </div>
                          </div>
                        </td>
                        <td className="px-8 py-6">
                          <span className="px-3 py-1 rounded-lg bg-slate-100 text-slate-600 text-[10px] font-black uppercase tracking-widest">
                            {row.room_number || 'N/A'}
                          </span>
                        </td>
                        <td className="px-8 py-6">
                          <div className="flex flex-col items-start gap-1">
                            <span className="text-sm font-black text-slate-900">₹{parseFloat(row.amount_paid).toLocaleString()}</span>
                            <div className="flex items-center gap-2 text-[10px] font-bold text-slate-400 uppercase tracking-tighter">
                              <span className="flex items-center gap-1"><Calendar size={10} /> {new Date(row.payment_date).toLocaleDateString()}</span>
                              <span className="flex items-center gap-1"><Clock size={10} /> {new Date(row.payment_date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                            </div>
                          </div>
                        </td>
                        <td className="px-8 py-6">
                          <div className="flex items-center gap-2">
                            <span className={cn(
                              "px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-[0.15em]",
                              row.payment_mode === 'Cash' ? "bg-emerald-50 text-emerald-600" : "bg-blue-50 text-blue-600"
                            )}>
                              {row.payment_mode}
                            </span>
                          </div>
                        </td>
                      </motion.tr>
                    ))
                  )}
                </AnimatePresence>
              </tbody>
            </table>
          </div>
        </section>
      </main>
    </div>
  );
};

export default FeeCollectionReport;
